enabled: true # Set to true to run the queries below instead of an interactive session
queries:
  - "bagpack"
  - "plants"
  - "bed"
  - "trophy"
  - "backpack"
  - "piano"
  - "plate"
  - "green ball"
  - "microwave"
  - "wooden board"
  - "sink"
  - "monitor"
  - "desk"